### ISSUE TITLE
How to get response of success.

### ISSUE THREAD

**Issue by amitinfo86** [gepo/apns-http2#3]
I am using following script to send push notification, its working fine. But there is no response of success, how can I enable it.
`require_once __DIR__ . '/vendor/autoload.php';
$client = new \Apns\Client(__DIR__ . '/certs/pushcert.pem', true);

$message = (new \Apns\Message())
    ->setDeviceIdentifier('some-device-token')   
    ->setAlert('Test message')
;
$response = $client->send($message);
`
If device token is incorrect its throwing fatal error, how can I handle this?  
How can I understand the flow of execution if I want to change something.

**Comment by gepo** [comment]
In case of invalid device token you catch an exception as you usually do. 'send' method returns true in case of success.

For flow of execution - could you provide an example of what are you trying to change?

**Comment by amitinfo86** [comment]
Thanks for the answer. You have created excellent library.
 
I am trying to achieve following points - 
-  If app is uninstall then I need to store device token, because there is no need to send push to this particular device. For now if app is uninstall I am still getting success message.

-

- For now i am using try catch block in following script to catch fatal error as follows
`$reason = array();
require_once __DIR__ . '/vendor/autoload.php';
try {
    $client = new \Apns\Client(__DIR__ . '/certs/pushcert.pem', true);

$message = (new \Apns\Message())
    ->setDeviceIdentifier('4C0D72782199966216992664F009335EA32EBDA4B05023A69029DE8D7C0D3353')
    //4C0D72782199966216992664F009335EA32EBDA4B05023A69029DE8D7C0D3353
    //->setDeviceIdentifier('4C0D72782199966216992664F009335EA32EBDA4B05023A69029DE8D7C0D3353')
    ->setAlert('Test message')
;

$response = $client->send($message);
if($response){
	 $reason['message'] =  'sent';  
	 echo json_encode($reason);
}
} catch (Exception $e) {
    $reason['reason'] =  $e->getMessage();  
    echo json_encode($reason);    
}`

- Is there a way to send push in bulk?

- If there is an error from APNS side then I am getting following 
Fatal error: Uncaught GuzzleHttp\Exception\ClientException: Client error: `POST https://api.development.push.apple.com/3/device/4C0D72782199966216992664F009335EA32EBDA4B05023A69029DE8D7C0D3350` resulted in a `400 Bad Request` response: {"reason":"BadDeviceToken"} in C:\myinstall\Apache24\htdocs\apns\vendor\guzzlehttp\guzzle\src\Exception\RequestException.php:113 Stack trace: #0 C:\myinstall\Apache24\htdocs\apns\vendor\guzzlehttp\guzzle\src\Middleware.php(65): GuzzleHttp\Exception\RequestException::create(Object(GuzzleHttp\Psr7\Request), Object(GuzzleHttp\Psr7\Response)) #1 C:\myinstall\Apache24\htdocs\apns\vendor\guzzlehttp\promises\src\Promise.php(203): GuzzleHttp\Middleware::GuzzleHttp\{closure}(Object(GuzzleHttp\Psr7\Response)) #2 C:\myinstall\Apache24\htdocs\apns\vendor\guzzlehttp\promises\src\Promise.php(156): GuzzleHttp\Promise\Promise::callHandler(1, Object(GuzzleHttp\Psr7\Response), Array) #3 C:\myinstall\Apache24\htdocs\apns\vendor\guzzlehttp\promises\src\TaskQueue.php(47): GuzzleHttp\Promise\Promise::GuzzleHttp in C:\myinstall\Apache24\htdocs\apns\vendor\gepo\apns-http2\src\ExceptionFactory.php on line 58

Thanks

**Comment by amitinfo86** [comment]
Where are we passing passphrase?

**Comment by jatinbphp** [comment]
@@uUnexpected HTTP/1.x request: POST /3/device/193d225834fc1f4410815eb8997d6d6639c616b9a8a27dd91401a568f99fd0eb @@uUnexpected HTTP/1.x request: POST /3/device/193d225834fc1f4410815eb8997d6d6639c616b9a8a27dd91401a568f99fd0eb @@uUnexpected HTTP/1.x request: POST /3/device/193d225834fc1f4410815eb8997d6d6639c616b9a8a27dd91401a568f99fd0eb 

I am getting this error.

**Comment by tlacroix** [comment]
@jatinbphp  You can check if the cURL version you have installed supports HTTP/2 or not like this:
```
<?php

if (!defined('CURL_HTTP_VERSION_2_0')) {
        define('CURL_HTTP_VERSION_2_0', 3);
}

$version = curl_version();

if ($version['features'] & constant('CURL_VERSION_HTTP2') !== 0) {
        echo 'HTTP/2 supported'.PHP_EOL;
} else {
        echo 'HTTP/2 not supported'.PHP_EOL;
}
?>
```

Also, since today (March 29, 2021), you'll need to have the AAA certificate authority installed. You can get it here: https://support.sectigo.com/Com_KnowledgeDetailPage?Id=kA03l00000117cL (the first one, name AAA)

On Ubuntu, you must put it in `/usr/local/share/ca-certificates/extra` (create the path if it doesn't exist), and run `update-ca-certificates`).

Also, you must absolutely set a topic for it to work. It's typically your bundle ID (ex. com.mycompany.myapp). I managed to get it a runtime like this:
```
$apnsClient = new ApnsClient(['/path/to/cert.pem', 'my-passphrase']);
...
if ($cert = openssl_x509_parse(file_get_contents($apnsClient->getSslCert()[0]))) {
    $topic = $cert['subject']['UID'];
}
```

Got it working today on Ubuntu 20.04 with stock php 7.4.3, with the `composer` installed version.
